# Generated by Django 3.1.7 on 2021-04-23 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_auto_20210423_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='countdown',
            field=models.TimeField(blank=True, null=True, verbose_name='时长'),
        ),
    ]
