# Generated by Django 3.1.7 on 2021-04-24 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_grade_all_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='passphrase',
            field=models.CharField(max_length=12, null=True, verbose_name='口令'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('3', 'difficult'), ('1', 'easy'), ('2', 'general')], max_length=10, verbose_name='等级'),
        ),
    ]
