# Generated by Django 3.1.7 on 2021-04-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_auto_20210424_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='countdown',
            field=models.DurationField(blank=True, null=True, verbose_name='时长'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('1', 'easy'), ('3', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
