# Generated by Django 3.1.7 on 2021-04-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0014_auto_20210424_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paper',
            name='passphrase',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='口令'),
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('1', 'easy'), ('2', 'general'), ('3', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
