# Generated by Django 3.1.7 on 2021-04-24 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_auto_20210424_1415'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paper',
            old_name='countdown',
            new_name='duration',
        ),
        migrations.AlterField(
            model_name='question',
            name='level',
            field=models.CharField(choices=[('2', 'general'), ('1', 'easy'), ('3', 'difficult')], max_length=10, verbose_name='等级'),
        ),
    ]
