# Generated by Django 3.1.7 on 2021-04-24 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_auto_20210424_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dept',
            field=models.CharField(choices=[('信息学院', '信息学院'), ('机械与自动控制学院', '机械与自动控制学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院'), ('服装学院', '服装学院'), ('法政学院', '法政学院'), ('马克思主义学院', '马克思主义学院')], default=None, max_length=20, verbose_name='学院'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dept',
            field=models.CharField(choices=[('信息学院', '信息学院'), ('机械与自动控制学院', '机械与自动控制学院'), ('外国语学院', '外国语学院'), ('理学院', '理学院'), ('服装学院', '服装学院'), ('法政学院', '法政学院'), ('马克思主义学院', '马克思主义学院')], default=None, max_length=20, verbose_name='学院'),
        ),
    ]
